name: 04 - Using Actions
on: workflow_dispatch
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version: '20.x'
          - name: Install Dependencies
            run: |
              npm ci
              npm install --save-dev vitest
              npm install --save-dev jsdom
              npm install --save-dev @testing-library/react
              npm install --save-dev @testing-library/jest-dom
              npm install --save-dev @types/jest
            working-directory: 04-using-actions/vite-project 
          - name: Run Unit Tests
            run: npm run test
            working-directory: 04-using-actions/vite-project