name: 13 - Using Caching
on: 
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Whether to execute cache step
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/vite-project
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
            - name: Setup Node
              uses: actions/setup-node@v4.2.0
            - name: Install dependencies
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to nnprod
              run: echo "Deploying to nonprod"
