name: 13 - Using Caching
on: 
    workflow_dispatch:
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Whether to execute cache step
            node-version:
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x
                description: Node version
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/vite-project
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
            - name: Setup Node
              uses: actions/setup-node@v4.2.0
              with: 
                node-version: ${{ inputs.node-version}}
            - name: Download cached dependencies
              id: cache
              if: ${{ inputs.use-cache }}
              uses: actions/cache@v3
              with:
                key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
                path: 13-caching/vite-project/node_modules
            - name: Install dependencies
              if: ${{steps.cache.outputs.cache-hit == 'true'}}
              run: |
                npm ci
                npm install --save-dev vitest
                npm install --save-dev jsdom
                npm install --save-dev @testing-library/react
                npm install --save-dev @testing-library/jest-dom
                npm install --save-dev @types/jest
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"
