name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      node-version:
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: "20.x"
        description: Node version
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step
jobs:
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 13-caching/vite-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{inputs.node-version}}
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v4.2.0
        with:
          path: "13-caching/vite-project/node_modules"
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
  install-deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
    defaults:
      run:
        working-directory: 13-caching/vite-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{inputs.node-version}}
      - name: Calculate cache key
        id: cache-key
        run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Download cached dependencies
        id: cache
        if: ${{inputs.use-cache}}
        uses: actions/cache@v4.2.0
        with:
          key: ${{steps.cache-key.outputs.CACHE_KEY}}
          path: "13-caching/vite-project/node_modules"
      - name: Install dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
  linting:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run: 
        working-directory: 13-caching/vite-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{inputs.node-version}}
      - name: Download cached dependencies
        uses: actions/cache@v4.2.0
        with:
          key: ${{ needs.install-deps.outputs.deps-cache-key}}
          path: "13-caching/vite-project/node_modules"
      - name: Testing
        run: npm run test
      - name: Linting
        run: echo "Linting..."



    