name: 14 - Working with Artifacts
on:
    workflow_dispatch:
env: 
    workflow_key: 'app-${{ github.sha }}'
    test-coverage-key: test-coverage-${{ github.sha }}

jobs: 
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-artifacts/react-app
        steps:
            - name: Checkout  code
              uses: actions/checkout@v4.2.2
            - name: Setup Node
              uses: actions/setup-node@v4.2.0
              with:
                node-version: 20.x
            - name: Download cached dependencies
              id: cache
              uses: actions/cache@v4.2.0
              with:
                key: deps-node-modules-${{hashFiles('14-artifacts/react-app/package-lock.json')}}
                path: 14-artifacts/react-app/node_modules
            - name: Install dependencies
              if: ${{steps.cache.outputs.cache-hit != 'true'}}
              run: npm ci  
            - name: Unit tests
              run: npx vitest --coverage
            - name: Upload test results
              uses: actions/upload-artifact@v4.2.0
              with: 
                name: ${{env.test-coverage-key}}
                path: 14-artifacts/react-app/coverage
            - name: Build Code
              run: npm run build
            - name: Upload build files
              uses: actions/upload-artifact@v4.6.0
              with:
                name: ${{env.workflow_key}}
                path: 14-artifacts/react-app/dist
    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Download build files
              uses: actions/download-artifact@v4.1.8
              with:
                name: ${{ env.workflow_key }}
                path: build
            - name: Show contents
              working-directory: 14-artifacts/react-app/dist
              run: ls -R
                


